# -*- coding: utf-8 -*-
"""kmeans clustering.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wum7G3KN3g1d6RSMtzVe--dSiIvaDJk9
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.preprocessing import LabelEncoder, StandardScaler

df=pd.read_csv('Mail_Customers.csv')

df.info()

df2 = pd.get_dummies(df['Genre'])
df = pd.concat((df,df2),axis = 1)
df = df.drop(['Genre'], axis = 1)
df.info()

X = df[['Age','Annual Income (k$)','Spending Score (1-100)']]

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

kmeans = KMeans(n_clusters=3)
kmeans.fit(X_scaled)
labels = kmeans.labels_
centers = kmeans.cluster_centers_

fig = plt.figure(figsize=(10, 6))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(X_scaled[:, 0], X_scaled[:, 1], X_scaled[:, 2], c=labels, cmap='viridis')
ax.scatter(centers[:, 0], centers[:, 1], centers[:, 2], c='red', s=200, alpha=0.75)
ax.set_xlabel('Age')
ax.set_ylabel('Estimated Salary')
ax.set_zlabel('Purchased')
plt.title('K-means Clustering')
plt.show()

Y = df[['Male','Annual Income (k$)','Spending Score (1-100)']]

scaler = StandardScaler()
Y_scaled = scaler.fit_transform(Y)

kmeans = KMeans(n_clusters=3)
kmeans.fit(X_scaled)
labels = kmeans.labels_
centers = kmeans.cluster_centers_

fig = plt.figure(figsize=(10, 6))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(Y_scaled[:, 0], Y_scaled[:, 1], Y_scaled[:, 2], c=labels, cmap='viridis')
ax.scatter(centers[:, 0], centers[:, 1], centers[:, 2], c='red', s=200, alpha=0.75)
ax.set_xlabel('Age')
ax.set_ylabel('Estimated Salary')
ax.set_zlabel('Purchased')
plt.title('K-means Clustering')
plt.show()

Z = df[['Female','Annual Income (k$)','Spending Score (1-100)']]

scaler = StandardScaler()
Z_scaled = scaler.fit_transform(Z)

kmeans = KMeans(n_clusters=3)
kmeans.fit(X_scaled)
labels = kmeans.labels_
centers = kmeans.cluster_centers_

fig = plt.figure(figsize=(10, 6))
ax = fig.add_subplot(111, projection='3d')
ax.scatter(Z_scaled[:, 0], Z_scaled[:, 1], Z_scaled[:, 2], c=labels, cmap='viridis')
ax.scatter(centers[:, 0], centers[:, 1], centers[:, 2], c='red', s=200, alpha=0.75)
ax.set_xlabel('Female')
ax.set_ylabel('Annual Income (k$)')
ax.set_zlabel('Purchased')
plt.title('Spending Score (1-100)')
plt.show()